# 相当于脚本用途的一个声明
name: Maven Central Repo Deployment
# 触发脚本的事件  这里为发布release之后触发
on:
  release:
    types: [released]
# 定义一个发行任务
jobs:
  publish:
    # 任务运行的环境
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          server-id: sonatype-nexus-staging
          server-username: ${{ secrets.OSSRH_USER }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: ${{ secrets.GPG_PASSWORD }}
      - name: Publish to Maven Central
        run: mvn --batch-mode --activate-profiles sonatype-nexus-staging clean deploy:deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}